services:
  postgres:
    image: postgres:17
    container_name: streamforge-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: streamforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: streamforge-rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"   #To communicate to rabbitmQ by springboot
      - "15672:15672"  # To communicate to rabbitMQ by browser 
#never ever the sprinboot communicates to rabbitMQ by 156272 and vicecersa
    environment:
      RABBITMQ_DEFAULT_USER: streamforge
      RABBITMQ_DEFAULT_PASS: streamforge_pass

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: