spring.application.name=StreamForge
streamforge.storage.upload-dir=uploads

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

streamforge.storage.max-file-size=524288000