    spring.application.name=StreamForge
    streamforge.storage.upload-dir=uploads
    streamforge.storage.processed-dir=storage/processed

    spring.servlet.multipart.max-file-size=500MB
    spring.servlet.multipart.max-request-size=500MB

    streamforge.storage.max-file-size=524288000


    # PostgreSQL Database Configuration
    spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/streamforge
    spring.datasource.username=postgres
    spring.datasource.password=postgres

    # JDBC Driver
    spring.datasource.driver-class-name=org.postgresql.Driver

    # JPA / Hibernate
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

    #RabbitMQ Connection
    spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
    spring.rabbitmq.port=${RABBITMQ_PORT:5672}
    spring.rabbitmq.username=${RABBITMQ_USERNAME:streamforge}
    spring.rabbitmq.password=${RABBITMQ_PASSWORD:streamforge_pass}